version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./db/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      # copy the sql script to fill tables
      - ./db/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
    ports:
      - "5432:5432"
    expose:
    - 5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-db_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123qwe}
      POSTGRES_DB: ${POSTGRES_DB:-tempo}
    networks:
      - postgres
  tempo-app:
    container_name: tempo_app
    links:
      - postgres
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile
      context: .
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tempo
      SPRING_DATASOURCE_USERNAME: db_user
      SPRING_DATASOURCE_PASSWORD: 123qwe
    ports:
      - "8081:8081"
    working_dir: /app
    networks:
        - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres-data:
